### ISSUE TITLE
Error in directive build

### ISSUE THREAD

**Issue by ackushiw** [thaiat/generator-angular-famous-ionic#122] opened 2015-02-04 01:10 UTC
Hey, I came across an error on line 10 of the directive js file

<pre>'use strict';
/*eslint consistent-this:[2,  "feed"] */
var directivename = 'directive';

module.exports = function(app) {

  // controller
  var controllerDeps = [];
  var controller = function() {
    var  = this;  //*** <b>ERROR HERE</b>
  };
  controller.$inject = controllerDeps;

  // directive
  var directiveDeps = [];
  var directive = function() {</pre>

I fixed with <pre> var vm = this; </pre>

**Comment by thaiat** [comment] 2015-02-04 10:53
hi  @ackushiw , the issue was fixed in this commit: https://github.com/thaiat/generator-angular-famous-ionic/commit/132ffdc6a268d3bf4c8762cb5ca2bce5b214283d
upgrade the generator to latest (1.3.2) and run again the scaffold for the directive, it should be fine

**Comment by thaiat** [comment] 2015-02-05 12:13
@ackushiw,  closing this meant time, feel free to reopen if the issue is still on your side

**Closed by thaiat** 2015-02-05 12:13 UTC
